# Generated by Django 3.1 on 2023-01-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anumandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anumandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerapp.anumandal')),
            ],
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerapp.block')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('husband_father_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('qualication', models.CharField(max_length=100)),
                ('mobile_number', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_number', models.PositiveIntegerField(unique=True)),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('currentaddress', models.CharField(blank=True, max_length=256, null=True)),
                ('permanentaddress', models.CharField(blank=True, max_length=256, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('holding_no', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('khata_no', models.CharField(blank=True, max_length=100, null=True)),
                ('khesra_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('thana', models.CharField(blank=True, max_length=100, null=True)),
                ('zila', models.CharField(blank=True, max_length=100, null=True)),
                ('computer_file', models.FileField(blank=True, upload_to='computer')),
                ('aadhar_file', models.FileField(blank=True, upload_to='aadhar')),
                ('matric_file', models.FileField(blank=True, upload_to='matric')),
                ('inter_file', models.FileField(blank=True, upload_to='inter')),
                ('graduation_file', models.FileField(blank=True, upload_to='graduation')),
                ('post_graduation_file', models.FileField(blank=True, upload_to='postgraduate')),
                ('caste_file', models.FileField(blank=True, upload_to='caste')),
                ('residence_file', models.FileField(blank=True, upload_to='residence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anumandal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerapp.anumandal')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerapp.block')),
                ('panchayat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerapp.panchayat')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
