# Generated by Django 3.1 on 2023-01-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0002_auto_20230131_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='vaccant',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
